name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make daily commit
        run: |
          git config user.email "vemurirenuka24@gmail.com"
          git config user.name "YourNewUsername"
          echo "Daily update: $(date)" >> daily_log.txt
          git add daily_log.txt
          git commit -m "🟩 Daily update - $(date '+%Y-%m-%d')"
          git push
